exclude: "^docs/|^migrations/|^migrations/versions/|^jupyter/"
default_stages: [commit]
default_language_version:
  python: python3.10


# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/compilerla/conventional-pre-commit
  rev: v2.2.0
  hooks:
    - id: conventional-pre-commit
      stages: [commit-msg]
      args: [feat, fix, ci, test, infra, hotfix, style, docs, merge, build, chore, perf, refactor, revert]

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    -   id: no-commit-to-branch
        args: ['-b', 'prod', '-b', 'sandbox']
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-added-large-files
    -   id: flake8
        args: [--max-line-length=160]
        additional_dependencies: [flake8-print, flake8-eradicate, flake8-builtins, flake8-commas, flake8-pie, flake8-mutable, flake8-bugbear, dlint]

- repo: https://github.com/PyCQA/autoflake
  rev: v2.1.1
  hooks:
    - id: autoflake
      args: ['--in-place', '--remove-all-unused-imports', '--remove-unused-variable']

- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
    - id: isort
      name: isort (python)
      language_version: python3.10
    - id: isort
      name: isort (cython)
      language_version: python3.10
      types: [cython]
    - id: isort
      name: isort (pyi)
      language_version: python3.10
      types: [pyi]

- repo: https://github.com/PyCQA/flake8
  rev: 6.0.0
  hooks:
    - id: flake8
      language_version: python3.10
      args: ["--config=setup.cfg"]
      additional_dependencies: [flake8-isort]
