# Generated by Django 4.2.16 on 2024-10-06 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdmissionProcess",
            fields=[
                (
                    "id",
                    models.CharField(max_length=80, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                ("subtitle", models.CharField(max_length=255)),
                ("short_name_admin", models.CharField(max_length=255)),
                ("short_name_display", models.CharField(max_length=255)),
                (
                    "application_target_type",
                    models.CharField(
                        choices=[("SCHOOL", "School"), ("PROGRAM", "Program")],
                        max_length=10,
                    ),
                ),
                (
                    "display_in_public_school_directory",
                    models.BooleanField(default=True),
                ),
            ],
        ),
    ]
